DELIMITER //
CREATE FUNCTION borrowStatus(borrowDate DATETIME, returnDate DATETIME)
RETURNS VARCHAR(20)
DETERMINISTIC
BEGIN
	CASE
		WHEN CURDATE() < DATE(returnDate) THEN RETURN 'Not Due';
		WHEN CURDATE() = DATE(returnDate) THEN RETURN 'Due';
		ELSE RETURN 'Overdue';
    END CASE;
    RETURN 'Good';
END
// DELIMITER ;